"""raw_messages: keep every inbound message before parsing

Revision ID: 1965608f8cb7
Revises: b6f72f816833
Create Date: 2026-10-01 18:22:44.348383
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1965608f8cb7'
down_revision: Union[str, None] = 'b6f72f816833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('chat_id', sa.String(length=32), nullable=True),
    sa.Column('sender_user_id', sa.String(length=32), nullable=True),
    sa.Column('sender_name', sa.String(length=80), nullable=True),
    sa.Column('prefix_detected', sa.String(length=10), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('txn_date_hint', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=20), nullable=True),
    sa.Column('rule', sa.String(length=60), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('txn_type', sa.Enum('DEBIT', 'CREDIT', name='transactiontype'), nullable=True),
    sa.Column('txn_mode', sa.Enum('UPI', 'CARD', 'NETBANKING', 'ATM', 'WALLET', 'CASH', 'IMPS', 'NEFT', 'RTGS', name='transactionmode'), nullable=True),
    sa.Column('account_last_four', sa.String(length=4), nullable=True),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('upi_ref', sa.String(length=100), nullable=True),
    sa.Column('upi_handle', sa.String(length=120), nullable=True),
    sa.Column('transfer_kind', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parser_version', sa.String(length=40), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_messages', schema=None) as batch_op:
        batch_op.create_index('idx_raw_parsed_at', ['parsed_at'], unique=False)
        batch_op.create_index('idx_raw_received', ['received_at'], unique=False)
        batch_op.create_index('idx_raw_verdict', ['verdict'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_messages_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_messages_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index('ux_raw_source_ext', ['source', 'external_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_messages', schema=None) as batch_op:
        batch_op.drop_index('ux_raw_source_ext')
        batch_op.drop_index(batch_op.f('ix_raw_messages_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_raw_messages_external_id'))
        batch_op.drop_index('idx_raw_verdict')
        batch_op.drop_index('idx_raw_received')
        batch_op.drop_index('idx_raw_parsed_at')

    op.drop_table('raw_messages')
    # ### end Alembic commands ###