"""initial schema

Revision ID: b6f72f816833
Revises: 
Create Date: 2026-10-01 16:35:35.878064
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b6f72f816833'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('EXPENSE', 'INCOME', 'TRANSFER', 'IGNORE', name='categorytype'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=30), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('idx_category_type', ['type'], unique=False)
        batch_op.create_index('uq_category_child_name', ['name', 'parent_id'], unique=True, sqlite_where=sa.text('parent_id IS NOT NULL'), postgresql_where=sa.text('parent_id IS NOT NULL'))
        batch_op.create_index('uq_category_root_name', ['name'], unique=True, sqlite_where=sa.text('parent_id IS NULL'), postgresql_where=sa.text('parent_id IS NULL'))

    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.Enum('CREDIT_CARD', 'DEBIT_CARD', 'SAVINGS', 'CURRENT', 'UPI', 'WALLET', name='accounttype'), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('default_cashback_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('default_cashback_type', sa.Enum('CASH', 'POINTS', 'WALLET', name='cashbacktype'), nullable=True),
    sa.Column('default_cashback_wallet', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('txn_type', sa.Enum('DEBIT', 'CREDIT', name='transactiontype'), nullable=False),
    sa.Column('txn_mode', sa.Enum('UPI', 'CARD', 'NETBANKING', 'ATM', 'WALLET', 'CASH', 'IMPS', 'NEFT', 'RTGS', name='transactionmode'), nullable=True),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('upi_ref', sa.String(length=100), nullable=True),
    sa.Column('txn_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('cashback_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cashback_type', sa.Enum('CASH', 'POINTS', 'WALLET', name='cashbacktype'), nullable=True),
    sa.Column('cashback_wallet', sa.String(length=50), nullable=True),
    sa.Column('cashback_status', sa.Enum('PENDING', 'RECEIVED', 'EXPIRED', name='cashbackstatus'), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('is_split_parent', sa.Boolean(), nullable=True),
    sa.Column('parent_txn_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['parent_txn_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_is_spam'), ['is_spam'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_message_id'), ['message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_needs_review'), ['needs_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_txn_timestamp'), ['txn_timestamp'], unique=False)

    op.create_table('merchant_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern')
    )
    with op.batch_alter_table('merchant_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_merchant_mapping_active', ['is_active'], unique=False)
        batch_op.create_index('idx_merchant_mapping_pattern', ['pattern'], unique=False)

    op.create_table('recurring_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('next_expected_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_recurring_next_date', ['next_expected_date'], unique=False)

    op.create_table('transaction_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('allocation_type', sa.Enum('EXPENSE_FOR', 'INCOME_FROM', 'PAID_BY', name='allocationtype'), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_allocations', schema=None) as batch_op:
        batch_op.create_index('idx_alloc_person', ['person_id'], unique=False)
        batch_op.create_index('idx_alloc_transaction', ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_allocations', schema=None) as batch_op:
        batch_op.drop_index('idx_alloc_transaction')
        batch_op.drop_index('idx_alloc_person')

    op.drop_table('transaction_allocations')
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_recurring_next_date')

    op.drop_table('recurring_transactions')
    with op.batch_alter_table('merchant_mappings', schema=None) as batch_op:
        batch_op.drop_index('idx_merchant_mapping_pattern')
        batch_op.drop_index('idx_merchant_mapping_active')

    op.drop_table('merchant_mappings')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_txn_timestamp'))
        batch_op.drop_index(batch_op.f('ix_transactions_needs_review'))
        batch_op.drop_index(batch_op.f('ix_transactions_message_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_is_spam'))

    op.drop_table('transactions')
    op.drop_table('accounts')
    op.drop_table('persons')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('uq_category_root_name', sqlite_where=sa.text('parent_id IS NULL'), postgresql_where=sa.text('parent_id IS NULL'))
        batch_op.drop_index('uq_category_child_name', sqlite_where=sa.text('parent_id IS NOT NULL'), postgresql_where=sa.text('parent_id IS NOT NULL'))
        batch_op.drop_index('idx_category_type')

    op.drop_table('categories')
    # ### end Alembic commands ###