import yaml

with open("render.yaml", encoding="utf-8") as fh:
    cfg = yaml.safe_load(fh)

svc = cfg["services"][0]
print("render.yaml parses OK\n")
print("  plan         :", svc["plan"])
print("  buildCommand :", svc["buildCommand"])
print("  startCommand :", svc["startCommand"])
print("  healthCheck  :", svc["healthCheckPath"])
print()
print("  envVars:")
for v in svc["envVars"]:
    if v.get("sync") is False:
        how = "YOU SET THIS"
    elif v.get("generateValue"):
        how = "auto-generated by Render"
    else:
        how = "fixed: " + str(v.get("value"))
    print("    {:<26} {}".format(v["key"], how))

need = [v["key"] for v in svc["envVars"] if v.get("sync") is False]
print()
print("  you must paste these:", ", ".join(need))